In [1]:
from __future__ import print_function
import torch

print("Completed import libs")


Completed import libs


In [6]:
x = torch.empty(5, 3) #5 * 3 행렬 생성 초기화 x
print(x)

tensor([[4.5305e+33, 2.9758e+29, 1.6097e+19],
        [1.6085e+19, 2.7909e+29, 1.6458e+19],
        [5.2033e+28, 2.7946e+20, 2.0535e-19],
        [1.8465e+20, 3.9592e-11, 4.7429e+30],
        [4.0658e+21, 2.5608e+17, 2.7518e+17]])


In [ ]:
x = torch.rand(5, 3) # 랜덤
print(x)

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)  #0 으로 초기화
print(x)

In [ ]:
x = torch.tensor([5.5, 3.0])
print(x)

In [10]:
y = x.new_ones(5, 3, dtype=torch.double) # 1 초기화 하되 x는 tensor instance이어야 함.
print(y)

x = torch.randn_like(y, dtype=torch.float) # 랜덤으로 x크기만큼 랜덤으로 생성
print(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8207, -0.3514,  1.4969],
        [-1.5687,  0.2686, -1.0631],
        [ 1.1298,  1.4899, -0.4362],
        [-0.4542,  0.3582, -0.5786],
        [-0.3260,  0.7840,  0.0642]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))